import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

export const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-purple-300 max-w-7xl ml-auto mr-auto p-3 min-h-screen flex flex-col ${inter.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
